// AUTH
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

// APP
export const SET_DAYS_EVENTS = 'SET_DAYS_EVENTS';
export const SET_GOOGLE_CAL_EVENTS = 'SET_GOOGLE_CAL_EVENTS';
export const SET_PAST_EVENTS = 'SET_PAST_EVENTS';

export const SET_DAYS_DATES = 'SET_DAYS_DATES';
export const SET_ACTIVE_CALL = 'SET_ACTIVE_CALL';
export const SET_CALL_EVENT_MODAL = 'SET_CALL_EVENT_MODAL';
export const CANCEL_CALL_EVENT_MODAL = 'CANCEL_CALL_EVENT_MODAL';
export const SAVE_CALL_EVENT_MODAL = 'SAVE_CALL_EVENT_MODAL';
export const SET_CALL_EVENT_INIT_STATE = 'SET_CALL_EVENT_INIT_STATE';
export const SET_FRAMEWORK_TEMPLATE = 'SET_FRAMEWORK_TEMPLATE'; // sets ActiveCall FrameworkTemplate

// framework template blocks
export const SET_FRAMEWORK_BLOCK = 'SET_FRAMEWORK_BLOCK';
export const SET_FRAMEWORK_BLOCKS = 'SET_FRAMEWORK_BLOCKS';
export const SET_ACTIVE_FRAMEWORK_BLOCK = 'SET_ACTIVE_FRAMEWORK_BLOCK';
export const REMOVE_FRAMEWORK_BLOCK = 'REMOVE_FRAMEWORK_BLOCK';
export const SET_FRAMEWORK_BLOCK_NAME = 'SET_FRAMEWORK_BLOCK_NAME';
export const SET_FRAMEWORK_BLOCK_TYPE = 'SET_FRAMEWORK_BLOCK_TYPE';

// framework template elements
export const SET_FRAMEWORK_ELEMENT = 'SET_FRAMEWORK_ELEMENT';
export const SET_FRAMEWORK_ELEMENTS = 'SET_FRAMEWORK_ELEMENTS';
export const SET_ACTIVE_FRAMEWORK_ELEMENT = 'SET_ACTIVE_FRAMEWORK_ELEMENT';
export const REMOVE_FRAMEWORK_ELEMENT = 'REMOVE_FRAMEWORK_ELEMENT';
export const SET_FRAMEWORK_ELEMENT_NAME = 'SET_FRAMEWORK_ELEMENT_NAME';
export const SET_FRAMEWORK_ELEMENT_TYPE = 'SET_FRAMEWORK_ELEMENT_TYPE';

// framework template battle cards
export const SET_FRAMEWORK_BATTLE_CARD = 'SET_FRAMEWORK_BATTLE_CARD';
export const SET_FRAMEWORK_BATTLE_CARD_NAME = 'SET_FRAMEWORK_BATTLE_CARD_NAME';
export const SET_ACTIVE_FRAMEWORK_BATTLE_CARD =
  'SET_ACTIVE_FRAMEWORK_BATTLE_CARD';
export const REMOVE_FRAMEWORK_BATTLE_CARD = 'REMOVE_FRAMEWORK_BATTLE_CARD';

// framework template battle card talk tracks
export const SET_FRAMEWORK_BATTLE_CARD_TALK_TRACKS =
  'SET_FRAMEWORK_BATTLE_CARD_TALK_TRACKS';
export const SET_FRAMEWORK_BATTLE_CARD_TALK_TRACK =
  'SET_FRAMEWORK_BATTLE_CARD_TALK_TRACK';
export const SET_ACTIVE_FRAMEWORK_BATTLE_CARD_TALK_TRACK =
  'SET_ACTIVE_FRAMEWORK_BATTLE_CARD_TALK_TRACK';
export const SET_FRAMEWORK_BATTLE_CARD_TALK_TRACK_NAME =
  'SET_FRAMEWORK_BATTLE_CARD_TALK_TRACK_NAME';
export const REMOVE_FRAMEWORK_BATTLE_CARD_TALK_TRACK =
  'REMOVE_FRAMEWORK_BATTLE_CARD_TALK_TRACK';

// active event
export const REMOVE_CALL_EVENT_ATTENDEE = 'REMOVE_CALL_EVENT_ATTENDEE';
export const UPDATE_CALL_EVENT_ELEMENT = 'UPDATE_CALL_EVENT_ELEMENT';
export const UPDATE_CALL_EVENT_ACTION = 'UPDATE_CALL_EVENT_ACTION';
export const UPDATE_CALL_EVENT_NOTE = 'UPDATE_CALL_EVENT_NOTE';
export const SET_CALL_EVENT_NOTE = 'SET_CALL_EVENT_NOTE';

// NOTIFICATIONS
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_EVENT_NOTIFICATION = 'SET_EVENT_NOTIFICATION';
export const CLOSE_EVENT_NOTIFICATION = 'CLOSE_EVENT_NOTIFICATION';
export const TOGGLE_NOTIFY_DRAWER = 'TOGGLE_NOTIFY_DRAWER';

// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const SET_ALERT_DIALOG = 'SET_ALERT_DIALOG';

// BUILDER
// templates
export const SET_TEMPLATES = 'SET_TEMPLATES';
export const SET_TEMPLATE = 'SET_TEMPLATE';
export const REMOVE_TEMPLATE = 'REMOVE_TEMPLATE';
export const SET_ACTIVE_TEMPLATE = 'SET_ACTIVE_TEMPLATE';
export const SET_TEMPLATE_NAME = 'SET_TEMPLATE_NAME';
export const ADD_FRAMEWORK_TEMPLATE = 'ADD_FRAMEWORK_TEMPLATE'; // adds edited FrameworkTemplate to builder

// added for node upgrade...
export const SET_TALK_TRACK = 'SET_TALK_TRACK';
export const REMOVE_TALK_TRACK = 'REMOVE_TALK_TRACK';

// blocks
export const SET_BLOCKS = 'SET_BLOCKS';
export const SET_BLOCK = 'SET_BLOCK';
export const REMOVE_BLOCK = 'REMOVE_BLOCK';
export const SET_ACTIVE_BLOCK = 'SET_ACTIVE_BLOCK';
export const SET_BLOCK_NAME = 'SET_BLOCK_NAME';
export const SET_BLOCK_TYPE = 'SET_BLOCK_TYPE';

// elements
export const SET_ELEMENTS = 'SET_ELEMENTS';
export const SET_ELEMENT = 'SET_ELEMENT';
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT';
export const SET_ACTIVE_ELEMENT = 'SET_ACTIVE_ELEMENT';
export const SET_ELEMENT_NAME = 'SET_ELEMENT_NAME';
export const SET_ELEMENT_TYPE = 'SET_ELEMENT_TYPE';

// battle cards
export const SET_BATTLE_CARD = 'SET_BATTLE_CARD';
export const SET_BATTLE_CARD_NAME = 'SET_BATTLE_CARD_NAME';
export const SET_ACTIVE_BATTLE_CARD = 'SET_ACTIVE_BATTLE_CARD';
export const SET_BATTLE_CARD_TALK_TRACKS = 'SET_BATTLE_CARD_TALK_TRACKS';
export const SET_BATTLE_CARD_TALK_TRACK = 'SET_BATTLE_CARD_TALK_TRACK';
export const REMOVE_BATTLE_CARD = 'REMOVE_BATTLE_CARD';
export const REMOVE_BATTLE_CARD_TALK_TRACK = 'REMOVE_BATTLE_CARD_TALK_TRACK';
export const SET_ACTIVE_BATTLE_CARD_TALK_TRACK =
  'SET_ACTIVE_BATTLE_CARD_TALK_TRACK';
export const SET_BATTLE_CARD_TALK_TRACK_NAME =
  'SET_BATTLE_CARD_TALK_TRACK_NAME';

// battle cards library
export const SET_LIBRARY_BATTLE_CARDS = 'SET_LIBRARY_BATTLE_CARDS';
export const SET_LIBRARY_BATTLE_CARD = 'SET_LIBRARY_BATTLE_CARD';
export const SET_ACTIVE_LIBRARY_BATTLE_CARD = 'SET_ACTIVE_LIBRARY_BATTLE_CARD';
export const SET_ACTIVE_LIBRARY_BATTLE_CARD_TALK_TRACK =
  'SET_ACTIVE_LIBRARY_BATTLE_CARD_TALK_TRACK';
export const ADD_LIBRARY_BATTLE_CARD = 'ADD_LIBRARY_BATTLE_CARD';
export const SET_LIBRARY_BATTLE_CARD_NAME = 'SET_LIBRARY_BATTLE_CARD_NAME';
export const REMOVE_LIBRARY_BATTLE_CARD = 'REMOVE_LIBRARY_BATTLE_CARD';
export const SET_FILTERED_LIBRARY_BATTLE_CARDS =
  'SET_FILTERED_LIBRARY_BATTLE_CARDS';

// battle card library talk tracks
export const SET_LIBRARY_BATTLE_CARD_TALK_TRACKS =
  'SET_LIBRARY_BATTLE_CARD_TALK_TRACKS';
export const SET_LIBRARY_BATTLE_CARD_TALK_TRACK =
  'SET_LIBRARY_BATTLE_CARD_TALK_TRACK';
export const SET_LIBRARY_BATTLE_CARD_ACTIVE_TALK_TRACK =
  'SET_LIBRARY_BATTLE_CARD_ACTIVE_TALK_TRACK';
export const REMOVE_LIBRARY_BATTLE_CARD_TALK_TRACK =
  'REMOVE_LIBRARY_BATTLE_CARD_TALK_TRACK';

// talk tracks library
export const SET_LIBRARY_TALK_TRACKS = 'SET_LIBRARY_TALK_TRACKS';
export const ALPHABETIZE_LIBRARY_TALK_TRACKS = 'ALPHABETIZE_LIBRARY_TALK_TRACKS';
export const SET_LIBRARY_TALK_TRACK = 'SET_LIBRARY_TALK_TRACK';
export const SET_ACTIVE_LIBRARY_TALK_TRACK = 'SET_ACTIVE_LIBRARY_TALK_TRACK';
export const ADD_LIBRARY_TALK_TRACK = 'ADD_LIBRARY_TALK_TRACK';
export const SET_LIBRARY_TALK_TRACK_NAME = 'SET_LIBRARY_TALK_TRACK_NAME';
export const REMOVE_LIBRARY_TALK_TRACK = 'REMOVE_LIBRARY_TALK_TRACK';
export const SET_FILTERED_LIBRARY_TALK_TRACKS =
  'SET_FILTERED_LIBRARY_TALK_TRACKS';

// NAV
// export const SET_MAIN_NAV_TAB_INDEX = 'SET_MAIN_NAV_TAB_INDEX';
export const SET_BUILDER_TAB_INDEX = 'SET_BUILDER_TAB_INDEX';

// WINDOW CALL EVENT
export const SET_ACTIVE_WIN_CALL_EVENT = 'SET_ACTIVE_WIN_CALL_EVENT';
export const SET_WIN_CALL_EVENT = 'SET_WIN_CALL_EVENT';
export const UPDATE_WIN_ELEMENT = 'UPDATE_WIN_ELEMENT';
export const REMOVE_CALL_EVENT_WINDOW_ATTENDEE =
  'REMOVE_CALL_EVENT_WINDOW_ATTENDEE';

// USER ACCOUNT
export const SET_USER_ACCOUNT = 'SET_USER_ACCOUNT';
export const SET_DAYS_EVENT_HISTORY = 'SET_DAYS_EVENT_HISTORY';
export const SET_DAYS_EVENT_FUTURE = 'SET_DAYS_EVENT_FUTURE';
